In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Principal component analysis

In [ ]:
# Survey 3

In [9]:
array = np.array([(1, 3), (1, -2), (-2, -1)])
f = np.array([(0.32), (0.95)])

In [12]:
array

array([[ 1,  3],
       [ 1, -2],
       [-2, -1]])

In [13]:
f

array([0.32, 0.95])

In [17]:
np.dot(array, f)

array([ 3.17, -1.58, -1.59])

In [19]:
#Survey 4 

In [27]:
a = np.array([(2), (3)])
b = np.array([(-3), (2)])

In [28]:
np.dot(a, b)

0

In [29]:
len_a = np.sqrt(a.dot(a))
len_b = np.sqrt(b.dot(b))

In [31]:
print(len_a)
print(len_b)

3.605551275463989
3.605551275463989


In [32]:
norm_a = a / len_a
norm_b = b / len_b

In [33]:
norm_a

array([0.5547002 , 0.83205029])

In [39]:
norm_b

array([-0.83205029,  0.5547002 ])

In [40]:
# Survey 6

In [56]:
z_1 = np.array([(3.17), (-1.58), (-1.59)]).reshape(3, 1)
f_1 = np.array([(0.32), 
                (0.95)]).reshape(2, 1)

In [58]:
z_1

array([[ 3.17],
       [-1.58],
       [-1.59]])

In [57]:
f_1

array([[0.32],
       [0.95]])

In [59]:
f_1_t = np.transpose(f_1)

In [60]:
np.dot(z_1, f_1_t)

array([[ 1.0144,  3.0115],
       [-0.5056, -1.501 ],
       [-0.5088, -1.5105]])